#!/bin/sh

if [ install = "$1" -o upgrade = "$1" ]; then 
  dpkg-divert --package yavdr-vdr --add --rename --divert /usr/lib/vdr/commands-loader.sh.real /usr/lib/vdr/commands-loader.sh
  dpkg-divert --package yavdr-vdr --add --rename --divert /usr/lib/vdr/config-loader.sh.real /usr/lib/vdr/config-loader.sh
  dpkg-divert --package yavdr-vdr --add --rename --divert /usr/lib/vdr/plugin-loader.sh.real /usr/lib/vdr/plugin-loader.sh
fi

exit 0
