#!/bin/sh

if [ remove = "$1" ]; then 
  dpkg-divert --package yavdr-vdr --remove --rename --divert /usr/lib/vdr/commands-loader.sh.dontremove /usr/lib/vdr/commands-loader.sh
  dpkg-divert --package yavdr-vdr --remove --rename --divert /usr/lib/vdr/config-loader.sh.dontremove /usr/lib/vdr/config-loader.sh
  dpkg-divert --package yavdr-vdr --remove --rename --divert /usr/lib/vdr/plugin-loader.sh.dontremove /usr/lib/vdr/plugin-loader.sh
fi

exit 0
